In [37]:
import pandas as pd
from ast import literal_eval

In [41]:

# Read CSV file into DataFrame
df = pd.read_csv('data/registers.csv')

# Convert string representations of lists in 'modules' column to actual lists
df['modules'] = df['modules'].apply(literal_eval)

# Explode the 'modules' column
df_expanded = df.explode('modules')

# Reset index to clean up the DataFrame
df_expanded.reset_index(drop=True, inplace=True)

# Specify the path for the new CSV file to be created
output_csv_file = 'expanded_modules_data.csv'

# Export the expanded DataFrame to a new CSV file
df_expanded.to_csv(output_csv_file, index=False)

print(f"Exported the expanded DataFrame to '{output_csv_file}' successfully.")

Exported the expanded DataFrame to 'expanded_modules_data.csv' successfully.

In [39]:
df_expanded.head(10)

,_id,name,email,password,role,checkreset,modules
0,6610e32fe10537e70a8169c8,Jennee Dunican,jdunican0@scribd.com,yJ7(%<kS2\,Employee,False,6610e8eee10537e770365f95
1,6610e32fe10537e70a8169c8,Jennee Dunican,jdunican0@scribd.com,yJ7(%<kS2\,Employee,False,6610e8eee10537e7c285591e
2,6610e32fe10537e70a8169c8,Jennee Dunican,jdunican0@scribd.com,yJ7(%<kS2\,Employee,False,6610e8eee10537e7c5210138
3,6610e32fe10537e70a8169c8,Jennee Dunican,jdunican0@scribd.com,yJ7(%<kS2\,Employee,False,6610e8eee10537e83cb671de
4,6610e32fe10537e70a8169c8,Jennee Dunican,jdunican0@scribd.com,yJ7(%<kS2\,Employee,False,6610e8eee10537e7916b9f41
5,6610e32fe10537e70a8169c9,Toddie Huston,thuston1@pen.io,vE2!>Ywc$Z,Employee,False,NaN
6,6610e32fe10537e70a8169ca,Augusto Adanet,aadanet2@instagram.com,xZ2@G_JA4$,Intern,True,6610e8eee10537e83e6ca272
7,6610e32fe10537e70a8169ca,Augusto Adanet,aadanet2@instagram.com,xZ2@G_JA4$,Intern,True,6610e8eee10537e71b41a7f1
8,6610e32fe10537e70a8169ca,Augusto Adanet,aadanet2@instagram.com,xZ2@G_JA4$,Intern,True,6610e8eee10537e8928bbcf1
9,6610e32fe10537e70a8169cb,Adara Carpenter,acarpenter3@smugmug.com,pZ5@VWpw8zlz>BWY,Employee,True,6610e8eee10537e8b1b75d77

In [40]:

# Read CSV file into DataFrame
df = pd.read_csv('data/modules.csv')

# Convert string representations of lists in 'modules' column to actual lists
df['trainer'] = df['trainer'].apply(literal_eval)

# Explode the 'modules' column
df_expanded = df.explode('trainer')

# Reset index to clean up the DataFrame
df_expanded.reset_index(drop=True)

# Specify the path for the new CSV file to be created
output_csv_file = 'expanded_trainer_data.csv'

# Export the expanded DataFrame to a new CSV file
df_expanded.to_csv(output_csv_file, index=False)

print(f"Exported the expanded DataFrame to '{output_csv_file}' successfully.")

In [36]:
df_expanded.head(10)

,_id,moduleName,startDate,endDate,moduleStatus,quizId,trainer
0,6610e8eee10537e70a8169f0,Baillie Ambage,11/7/2023,11/2/2023,pending,6610e2f9e10537e83cb671b5,6610e32fe10537e83cb671b8
0,6610e8eee10537e70a8169f0,Baillie Ambage,11/7/2023,11/2/2023,pending,6610e2f9e10537e83cb671b5,6610e330e10537e7a67f3c09
0,6610e8eee10537e70a8169f0,Baillie Ambage,11/7/2023,11/2/2023,pending,6610e2f9e10537e83cb671b5,6610e335e10537e740772aa4
1,6610e8eee10537e85f4fe21b,Jesus Cline,1/14/2024,5/26/2023,pending,6610e2f9e10537e6d7ef0f84,6610e330e10537e6f9e783bb
1,6610e8eee10537e85f4fe21b,Jesus Cline,1/14/2024,5/26/2023,pending,6610e2f9e10537e6d7ef0f84,6610e330e10537e7b003c49e
1,6610e8eee10537e85f4fe21b,Jesus Cline,1/14/2024,5/26/2023,pending,6610e2f9e10537e6d7ef0f84,6610e32fe10537e7c5210115
1,6610e8eee10537e85f4fe21b,Jesus Cline,1/14/2024,5/26/2023,pending,6610e2f9e10537e6d7ef0f84,6610e330e10537e7b003c4a1
1,6610e8eee10537e85f4fe21b,Jesus Cline,1/14/2024,5/26/2023,pending,6610e2f9e10537e6d7ef0f84,6610e32fe10537e8c57ab127
2,6610e8eee10537e7916b9f41,Edyth Phoenix,5/20/2023,2/7/2024,ongoing,6610e2f9e10537e875099976,6610e32fe10537e71b41a7cd
2,6610e8eee10537e7916b9f41,Edyth Phoenix,5/20/2023,2/7/2024,ongoing,6610e2f9e10537e875099976,6610e330e10537e6f9e783bc

In [ ]:
import snowflake.connector
import psycopg2
import csv
from io import StringIO
import pandas as pd
snowflake_connection = snowflake.connector.connect(
            user='',
            password='',
            account='',
            warehouse='COMPUTE_WH',
            database='TESTDATABASE',
            schema='Public',
            role='ACCOUNTADMIN'
        )
snowflake_cursor = snowflake_connection.cursor()
 
 
# Check Snowflake connection
try:
    snowflake_connection
    print("Connection to Snowflake successful!")
   
except Exception as e:
    print(f"Error connecting to Snowflake: {str(e)}")
 
 
try:
    # Connect to PostgreSQL
    pg_conn = psycopg2.connect(
        dbname='testdb',
        user='postgres',
        password='',
        host='localhost',
        port='5432'  # Default PostgreSQL port
    )
 
    # Create a cursor object using the connection
    pg_cursor = pg_conn.cursor()
    print("Connection to PostgreSQL successful.")
except psycopg2.Error as e:
    print("Error connecting to PostgreSQL:", e)
pg_cursor.execute("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE'")
tables = pg_cursor.fetchall()
for table in tables:
    table_name = table[0]
    # Read data from the table into a pandas DataFrame
    df = pd.read_sql(f'SELECT * FROM {table_name}', pg_conn)
    # Export DataFrame to CSV
    df.to_csv(f'staging/{table_name}.csv', index=False)
    print(f"Table '{table_name}' exported to CSV successfully.")
pg_conn.close()
import os
staging_folder = 'staging/'  # Change this to your actual staging folder path
 
# Get a list of all CSV files in the staging folder
csv_files = [file for file in os.listdir(staging_folder) if file.endswith('.csv')]
os.path.splitext(csv_files[0])[0]
temp = pd.read_csv(os.path.join(staging_folder, csv_files[0]))
for csv_file in csv_files:
    table_name = os.path.splitext(csv_file)[0]  # Use CSV file name as table name
   
    # Read CSV file into DataFrame
    df = pd.read_csv(os.path.join(staging_folder, csv_file))
   
    # Create table in Snowflake
    create_table_query = f"CREATE TABLE {table_name} ("
    for column in df.columns:
        create_table_query += f"{column} VARCHAR,"
    create_table_query = create_table_query[:-1]  # Remove trailing comma
    create_table_query += ")"
 
    # print(create_table_query)
    # break
    snowflake_cursor.execute(create_table_query)
    print(f"Table '{table_name}' created in Snowflake.")
   
    # Insert data into Snowflake table
    snowflake_cursor.executemany(f"INSERT INTO {table_name} VALUES ({','.join(['%s']*len(df.columns))})", df.values.tolist())
    print(f"Data inserted into table '{table_name}' in Snowflake.")
   
# Commit changes
snowflake_connection.commit()
# Close cursor and connection
snowflake_connection.close()
pg_conn.close()